# Generated by Django 4.2.23 on 2025-07-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(max_length=12, unique=True)),
            ],
            options={
                'db_table': 'rooms',
                'ordering': ['pk', 'number'],
                'indexes': [models.Index(fields=['number'], name='rooms_number_18c980_idx')],
            },
        ),
    ]
