# Generated by Django 4.2.23 on 2025-07-31 07:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['pk', 'number', 'updated_at']},
        ),
        migrations.AddField(
            model_name='room',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['updated_at'], name='rooms_updated_66817b_idx'),
        ),
    ]
