# Generated by Django 4.2.23 on 2025-08-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_alter_room_options_room_updated_at_alter_room_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['pk', 'number', 'updated_at', 'language']},
        ),
        migrations.AddField(
            model_name='room',
            name='language',
            field=models.CharField(default='python'),
        ),
    ]
