# Generated by Django 4.2.23 on 2025-08-01 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room', '0002_alter_room_options_room_updated_at_alter_room_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True, default='')),
                ('output', models.TextField(blank=True, default='')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='room.room')),
            ],
            options={
                'db_table': 'contents',
                'ordering': ['pk', 'room_id', 'code', 'output'],
                'indexes': [models.Index(fields=['room_id'], name='contents_room_id_c5198a_idx')],
            },
        ),
    ]
